chore: Update

diff --git a/.github/workflows/tag-and-release.yml b/.github/workflows/tag-and-release.yml
--- a/.github/workflows/tag-and-release.yml
+++ b/.github/workflows/tag-and-release.yml
@@ -1,4 +1,4 @@
-name: Release please
+name: Release Please
 
 on:
   push:
@@ -27,8 +27,11 @@ jobs:
     needs: release-please
     if: ${{ needs.release-please.outputs.release_created }}
     runs-on: macos-latest
+    permissions:
+      contents: write 
     steps:
       - uses: actions/checkout@v4
+      
       - name: Set up Go
         uses: actions/setup-go@v5
         with:
@@ -41,8 +44,15 @@ jobs:
         run: |
           go build -o cirr-darwin-arm64
 
+      - name: Verify Binary Exists
+        run: |
+          if [ ! -f cirr-darwin-arm64 ]; then
+            echo "Error: Binary 'cirr-darwin-arm64' was not created."
+            exit 1
+          fi
+
       - name: Upload Release Asset
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          gh release upload ${{ needs.release-please.outputs.tag_name }} cirr-darwin-arm64
+          gh release upload ${{ needs.release-please.outputs.tag_name }} cirr-darwin-arm64 --clobber
